before_install: gem install bundler --pre

# request headless test
before_script:
  - "sh -e /etc/init.d/xvfb start"
  - "bundle exec rake test_app"
  
script:
 - "cp config/alipay.yml.example config/alipay.yml 2>&1"
 - "DISPLAY=:99.0 bundle exec rake"

notifications:
  email:
    - lanvige@gmail.com

branches:
  only:
    - master

rvm:
  - 1.9.2
  - 1.9.3

timeouts:
  bundle: 600